[workspace]
members = [
    "tensor-rs",
    "par-iter",
    "small-vec"
]


[workspace.dependencies]
par_iter = { path = "par-iter" }
small_vec = { path = "small-vec" }
tensor_rs = { path = "tensor-rs" }